### ISSUE TITLE
There is a problem

### ISSUE THREAD

**Issue by Techno11** [orange-alliance/TOA-Text#8]
Not sure what, but i think there is one.

**Comment by Nate2019** [comment]
uh. Texts are coming through. What's this problem?

Edit: I think you may be the problem Soren?

**Comment by Huppdo** [comment]
Soren fix it. Python best language

**Comment by Techno11** [comment]
Python is wierd

**Comment by Techno11** [comment]
This is still a problem

**Comment by Huppdo** [comment]
Nope, it clearly says non issue
